version: "3.8"
services:
  mysql:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - ${DB_PORT}:3306
    working_dir: /app
    volumes:
      - "db:/var/lib/mysql"
      - "./db/schema.sql:/docker-entrypoint-initdb.d/01.sql"
      - "./config/my.cnf:/etc/mysql/conf.d/my.cnf"
      - ".:/app:cached"
    healthcheck:
      start_period: 10s
      interval: 10s
      timeout: 10s
      retries: 12
      test:
        - CMD
        - mysqladmin
        - ping
        - -h
        - localhost
volumes:
  db:
    driver: local
